# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import datetime


@dataclasses.dataclass()
class Author:
    id: int
    name: str
    born_on: datetime.date
    updated_at: datetime.datetime | None


@dataclasses.dataclass()
class Book:
    id: int
    author_id: int
    title: str
    published_at: datetime.datetime
