# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
import dataclasses
import datetime
from typing import cast

import sqlalchemy
import sqlalchemy.orm

from python import models


GET_BOOK_WITH_AUTHOR_DATES = """-- name: get_book_with_author_dates \\:one
SELECT
    books.id, books.author_id, books.title, books.published_at,
    authors.id, authors.name, authors.born_on, authors.updated_at
FROM books
JOIN authors ON books.author_id = authors.id
WHERE books.id = :p1
"""


@dataclasses.dataclass()
class GetBookWithAuthorDatesRow:
    books: models.Book
    authors: models.Author


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def get_book_with_author_dates(self, *, id: int) -> GetBookWithAuthorDatesRow | None:
        row = self._conn.execute(sqlalchemy.text(GET_BOOK_WITH_AUTHOR_DATES), {"p1": id}).first()
        if row is None:
            return None
        return GetBookWithAuthorDatesRow(
            books=models.Book(
                id=cast(int, row[0]),
                author_id=cast(int, row[1]),
                title=cast(str, row[2]),
                published_at=cast(datetime.datetime, row[3]),
            ),
            authors=models.Author(
                id=cast(int, row[4]),
                name=cast(str, row[5]),
                born_on=cast(datetime.date, row[6]),
                updated_at=cast(datetime.datetime | None, row[7]),
            ),
        )
