# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import datetime


@dataclasses.dataclass()
class File:
    id: int
    name: str
    size: int
    data: memoryview | None
    is_active: bool | None
    created_at: datetime.datetime
    rating: float | None
    metadata: str | None
