# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
from collections.abc import Iterator

import sqlalchemy
import sqlalchemy.orm

from python import models


GET_FILE = """-- name: get_file \\:one
SELECT id, name, size, data, is_active, created_at, rating, metadata FROM files
WHERE id = ?
"""


LIST_FILES = """-- name: list_files \\:many
SELECT id, name, size, data, is_active, created_at, rating, metadata FROM files
ORDER BY name
"""


class Querier:
    _conn: sqlalchemy.engine.Connection | sqlalchemy.orm.Session

    def __init__(self, conn: sqlalchemy.engine.Connection | sqlalchemy.orm.Session):
        self._conn = conn

    def get_file(self, *, id: int) -> models.File | None:
        row = self._conn.execute(sqlalchemy.text(GET_FILE), {"p1": id}).first()
        if row is None:
            return None
        return models.File(
            id=row[0],
            name=row[1],
            size=row[2],
            data=row[3],
            is_active=row[4],
            created_at=row[5],
            rating=row[6],
            metadata=row[7],
        )

    def list_files(self) -> Iterator[models.File]:
        result = self._conn.execute(sqlalchemy.text(LIST_FILES))
        for row in result:
            yield models.File(
                id=row[0],
                name=row[1],
                size=row[2],
                data=row[3],
                is_active=row[4],
                created_at=row[5],
                rating=row[6],
                metadata=row[7],
            )
