# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic


class User(pydantic.BaseModel):
    id: int
    name: str
    email: str | None
    age: int | None
    created_at: pydantic.AwareDatetime
