# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
from collections.abc import Iterator

import sqlalchemy
import sqlalchemy.orm

from python import models


GET_EVENT = """-- name: get_event \\:one
SELECT id, name, created_at, updated_at FROM events
WHERE id = ?
"""


LIST_EVENTS = """-- name: list_events \\:many
SELECT id, name, created_at, updated_at FROM events
ORDER BY created_at
"""


class Querier:
    _conn: sqlalchemy.engine.Connection | sqlalchemy.orm.Session

    def __init__(self, conn: sqlalchemy.engine.Connection | sqlalchemy.orm.Session):
        self._conn = conn

    def get_event(self, *, id: int) -> models.Event | None:
        row = self._conn.execute(sqlalchemy.text(GET_EVENT), {"p1": id}).first()
        if row is None:
            return None
        return models.Event(
            id=row[0],
            name=row[1],
            created_at=row[2],
            updated_at=row[3],
        )

    def list_events(self) -> Iterator[models.Event]:
        result = self._conn.execute(sqlalchemy.text(LIST_EVENTS))
        for row in result:
            yield models.Event(
                id=row[0],
                name=row[1],
                created_at=row[2],
                updated_at=row[3],
            )
