# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import datetime
import enum


class Status(str, enum.Enum):
    """Venues can be either open or closed"""
    OPEN = "op!en"
    CLOSED = "clo@sed"


@dataclasses.dataclass()
class City:
    slug: str
    name: str


@dataclasses.dataclass()
class Venue:
    """Venues are places where muisc happens"""
    id: int
    status: Status
    statuses: list[Status] | None
    # This value appears in public URLs
    slug: str
    name: str
    city: str
    spotify_playlist: str
    songkick_id: str | None
    tags: list[str] | None
    created_at: datetime.datetime
